spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wllxy0907
    hikari:
      #数据库名
      pool-name: DataHikari
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最大时间,0表示永久存活
      max-lifetime: 180000
      #最大连接数
      maximum-pool-size: 10
      #连接超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/seckill
  redis:
    host: 192.168.64.128
    port: 6379
    lettuce:
      pool:
        max-active: 16
        max-wait: 100000ms
        max-idle: 200
        min-idle: 5
    #password: wllxy0907
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
mybatis-plus:
  mapper-location: classpath*:/mapper/*Mapper.xml
  #
  type-aliases-package: com.wang.seckill.pojo
logging:
  level:
    com.wang.seckill.mapper: debug
server:
  port: 8080